name: curved_navigation_rail
description: Stunning Animating Curved Shape Navigation Rail. Adjustable color, background color, animation curve, animation duration.
version: 2.0.1
homepage: https://github.com/gangyistudios/curved_navigation_rail
repository: https://github.com/gangyistudios/curved_navigation_rail

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
